Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCProjectHamburger.Data;
using MVCProjectHamburger.Models.Entities.Concrete;

namespace MVCProjectHamburger.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MenuController : Controller
    {
        private readonly HamburgerDbContext _context;

        public MenuController(HamburgerDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Menu
        public async Task<IActionResult> Index()
        {
              return _context.Menus != null ? 
                          View(await _context.Menus.ToListAsync()) :
                          Problem("Entity set 'HamburgerDbContext.Menus'  is null.");
        }

        // GET: Admin/Menu/Details/5
       

        // GET: Admin/Menu/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Menu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Price,CoverImage,ID")] Menu menu, IFormFile ImageName)
        {
            _context.Menus.Add(menu);
            Guid guid = Guid.NewGuid();
            string newFileName = guid.ToString() + "_" + ImageName.FileName;
            menu.CoverImage = newFileName;

            FileStream st = new FileStream("wwwroot/HamburgerCoverImages/" + newFileName, FileMode.Create);
            await ImageName.CopyToAsync(st);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Admin/Menu/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);
        }

        // POST: Admin/Menu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Price,CoverImage,ID")] Menu menu,IFormFile ImgName)
        {
            if (id != menu.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    Guid guid = Guid.NewGuid();
                    string newFileName = guid.ToString() + "_" + ImgName.FileName;
                    menu.CoverImage = newFileName;

                    FileStream st = new FileStream("wwwroot/HamburgerCoverImages/" + newFileName, FileMode.Create);
                    await ImgName.CopyToAsync(st);
                   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menu);
        }

        // GET: Admin/Menu/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.ID == id);


            foreach (MenuOrder item in _context.MenuOrders.ToList())
            {
                if (item.MenuID == id)
                {
                    _context.MenuOrders.Remove(item);
                    
                }
            }

            foreach (ShoppingCart item in _context.ShoppingCarts.ToList())
            {
                if (item.MenuOrder.MenuID == id)
                {
                    _context.ShoppingCarts.Remove(item);
                   
                }
            }

            _context.SaveChanges();

            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Admin/Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Menus == null)
            {
                return Problem("Entity set 'HamburgerDbContext.Menus'  is null.");
            }
            var menu = await _context.Menus.FindAsync(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
          return (_context.Menus?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Areas/User/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCProjectHamburger.Data;
using MVCProjectHamburger.Models.Entities.Concrete;
using MVCProjectHamburger.Models.Enums;
using MVCProjectHamburger.Models.ViewModels;

namespace MVCProjectHamburger.Areas.User.Controllers
{
    [Area("User")]

    public class OrderController : Controller
    {
        private readonly HamburgerDbContext _context;
        private readonly UserManager<AppUser> userManager;

        public OrderController(HamburgerDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            this.userManager = userManager;

        }

        // GET: User/Order
        public async Task<IActionResult> Index()
        {
            var hamburgerDbContext = _context.Orders.Include(o => o.AppUser).Include(o => o.OrderMenus).Include(o => o.OrderExtraIngredients);
            return View(await hamburgerDbContext.ToListAsync());
        }

        public IActionResult GetMenu()
        {
            List<Menu> menu = _context.Menus.ToList();
            return PartialView("_GetMenuPartial", menu);
        }

        public IActionResult GetExtraIngredient()
        {
            List<ExtraIngredient> extraIngredients = _context.ExtraIngredients.ToList();
            return PartialView("_GetExtraIngredientPartial", extraIngredients);
        }


        [HttpPost]
        public IActionResult AddToOrder(int menuID, int number, int menuSize)
        {
            if (menuSize == 0)
            {
                var sortedOrders = _context.Orders.OrderBy(o => o.ID);
                Order od = sortedOrders.LastOrDefault();
                _context.ExtraIngredientOrders.Add(new ExtraIngredientOrder { AppUserID = GetUserID(), ExtraIngredientID = menuID, Number = number, OrderID = od.ID });
                _context.SaveChanges();

                var lastExtraOrder=_context.ExtraIngredientOrders.OrderBy(o => o.OrderID).LastOrDefault();

                ExtraIngredient extra = _context.ExtraIngredients.Find(menuID);
                od.TotalPrice += extra.Price * number;
                od.AppUserID= GetUserID();
                _context.Orders.Update(od);
                _context.SaveChanges();

                ShoppingCart cart = new ShoppingCart();
                cart.OrderId = od.ID;
                cart.Name=extra.Name;
                cart.TotalPrice = extra.Price * number;
                cart.Number=number;
                cart.ExtraIngredientOrderId = lastExtraOrder.ID;
                _context.ShoppingCarts.Add(cart);
                _context.SaveChanges();
                return RedirectToAction("ShoopingCart", new { id = od.ID });

            }
            else
            {

                var sortedOrders = _context.Orders.OrderBy(o => o.ID);
                Order od = sortedOrders.LastOrDefault();

                _context.MenuOrders.Add(new MenuOrder { AppUserID = GetUserID(), MenuID = menuID, Number = number, MenuSizes = (MenuSize)EnumBelirle(menuSize), OrderID = od.ID });
                _context.SaveChanges();

                var lastMenuOrder = _context.MenuOrders.OrderBy(o => o.ID).LastOrDefault();

                Menu menu = _context.Menus.Find(menuID);
                od.TotalPrice += (menu.Price + menuSize) * number;
                od.AppUserID = GetUserID();
                _context.Orders.Update(od);
                _context.SaveChanges();

                ShoppingCart cart = new ShoppingCart();
                cart.OrderId = od.ID;
                cart.Name = menu.Name;
                cart.TotalPrice = (menu.Price + menuSize) * number;
                cart.Number = number;
                cart.MenuSize = EnumBelirle(menuSize).ToString();
                cart.MenuOrderId = lastMenuOrder.ID;
                _context.ShoppingCarts.Add(cart);
                _context.SaveChanges();

                return RedirectToAction("ShoopingCart", new { id = od.ID });
            }

        }
        public IActionResult ShoopingCart(string? idd)
        {

            List<Order> orders = _context.Orders.OrderBy(x=>x.ID).ToList();
            int lastId = orders.Last().ID;

            List<ShoppingCart> orderList = _context.ShoppingCarts.Where(x => x.OrderId == lastId).ToList();
            return View(orderList);

        }
        [HttpPost]
        public IActionResult ShoopingCart()
        {
            Order od = new Order();
            od.TotalPrice = 0;
            _context.Orders.Add(od);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult NewOrder()
        {
            Order od = new Order();
            od.TotalPrice = 0;
            _context.Orders.Add(od);
            _context.SaveChanges();
            return NoContent();
        }
        public IActionResult Edit(int id)
        {
            ShoppingCart sc = _context.ShoppingCarts.Include(o => o.Order).Include(o => o.MenuOrder).Include(o => o.ExtraIngredientOrder).FirstOrDefault(x => x.ID == id);
            if (sc != null)
            {
                ShoppingCartVM VM = new ShoppingCartVM();
                VM.Id = id;
                VM.Number = sc.Number;
                if (sc.MenuSize != null)
                {
                    VM.MenuSize = sc.MenuSize;
                }
                VM.TotalPrice = sc.TotalPrice;
                VM.MenuOrder = sc.MenuOrder;
                VM.ExtraIngredientOrder = sc.ExtraIngredientOrder;
                VM.Order = sc.Order;
                return View(VM);

            }
            TempData["info"] = "There is no User to update";
            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult Edit(ShoppingCartVM vm)
        {
            int deger;
            ShoppingCart cart = _context.ShoppingCarts.Include(o => o.Order).Include(o => o.MenuOrder).Include(o => o.ExtraIngredientOrder).FirstOrDefault(x => x.ID == vm.Id);

            cart.Number = vm.Number;
            cart.MenuSize = vm.MenuSize;
            if (cart.MenuSize != null)
            {
                Menu menu = _context.Menus.Find(cart.MenuOrder.MenuID);
                cart.MenuSize = EnumBelirle(int.Parse(vm.MenuSize)).ToString();
                cart.TotalPrice = vm.Number * (menu.Price + int.Parse(vm.MenuSize));
            }
            else
            {
                ExtraIngredient ex = _context.ExtraIngredients.Find(cart.ExtraIngredientOrder.ExtraIngredientID);
                cart.TotalPrice = vm.Number * ex.Price;
            }
            _context.ShoppingCarts.Update(cart);
            _context.SaveChanges();


            Order od = _context.Orders.Find(cart.OrderId);
            List<ShoppingCart> carts = _context.ShoppingCarts.Where(x => x.OrderId == cart.OrderId).ToList();
            od.TotalPrice = 0;
            foreach (ShoppingCart item in carts)
            {
                od.TotalPrice += item.TotalPrice;

            }
            _context.Orders.Update(od);
            _context.SaveChanges();


            return RedirectToAction("ShoopingCart", new { id = cart.OrderId });


        }

        public ActionResult Delete(int id)
        {
            ShoppingCart sc = _context.ShoppingCarts.Find(id);
            Order od = _context.Orders.Find(sc.OrderId);

            if (sc != null)
            {
                _context.ShoppingCarts.Remove(sc);
                _context.SaveChanges();
                List<ShoppingCart> carts = _context.ShoppingCarts.Where(x => x.OrderId == sc.OrderId).ToList();
                od.TotalPrice = 0;
                foreach (ShoppingCart item in carts)
                {
                    od.TotalPrice += item.TotalPrice; 

                }
                _context.Orders.Update(od);
                _context.SaveChanges();
                return RedirectToAction("ShoopingCart", new { id = sc.OrderId });
            }
            else
            {
                return RedirectToAction("ShoopingCart", new { id = sc.OrderId });
            }
        }
        private Enum EnumBelirle(int sayi)
        {
            if (sayi == 1)
            {
                return MenuSize.Small;
            }
            else if (sayi == 10)
            {
                return MenuSize.Medium;
            }
            else
            {
                return MenuSize.Large;
            }
        }

        private int GetUserID()
        {
            return int.Parse(userManager.GetUserId(User));
        }
        


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> AvocadoBurger House </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCProjectHamburger.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.1/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <style>
        .navbar {
            background-color: #5c1212 !important; /* Add !important to override other conflicting styles */
        }

        .hover-effect:hover {
            color: red;
        }

        .text-font {
            font-family: Arial;
            color: darkred;
        }
    </style>

</head>
<body>
    <header class="m-3" >
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <a class="navbar-brand">
                        <img src="/HamburgerCoverImages/LogoSonHal.png" width="160px" height="100px" />
                    </a>
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" style="font-size:30px;font-weight:bold;color:white" asp-action="Index"> Avocado Burger House </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle font-weight-bold text-light text-bold" style="color:white; font-size:30px" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Control
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Menu" asp-action="Index">Add Menu</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="ExtraIngredient" asp-action="Index">Add Extra Ingredient</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Accountancy">Accountancy</a>
                                </div>
                            </li>
                        }
                        else if(User.IsInRole("User"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle font-weight-bold text-light text-bold " style="color:white; font-size:30px" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User Control
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="User" asp-controller="Order" asp-action="Index"> Menu </a>
                                    <a class="dropdown-item" asp-area="User" asp-controller="Order" asp-action="ShoopingCart"> Shopping Cart </a>
                                </div>
                            </li>
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>


    <div class="container">

        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>


    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-end ">
            <!-- Left -->
            
            <!-- Left -->
            <!-- Right -->
            <div>                
                <a href="https://www.linkedin.com/in/erdemhursutefendioglu/" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/ErdyEe" class="me-4 text-reset" target="_blank" >
                    <i class="fab fa-github"></i>
                </a>
                <span style="padding-right: 50px;"></span>
                <a href="https://www.linkedin.com/in/irem-ilgin-b12460175/" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/iremilgin" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
                <span style="padding-right: 50px;"></span>
                <a href="https://www.linkedin.com/in/yunus-kılıç-250242217/" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/yunuskilic10" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <style>
            .d-flex p {
                display: inline-block;
                margin: 0;
                padding: 5px;
            }
        </style>
        <section class="d-flex justify-content-end p-2 border-bottom">
            <div>
                <p>Erdem</p>
                <span style="padding-right: 85px;"></span>
                <p>İrem</p>
                <span style="padding-right: 85px;"></span>
                <p>Yunus</p>
                <span style="padding-right: 15px;"></span>
            </div>
        </section>

        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i> AvocadoBurger House
                        </h6>
                        <p>
                            Welcome to the world of AvocadoBurger House! In this special foreword, we want to share the story of our restaurant and our mission with you.
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a href="#!" class="text-reset"> Menus </a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset"> Extra Ingredients </a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4"> Contact </h6>
                        <p><i class="fas fa-home me-3"></i> Istanbul, Suadiye </p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            bilgeadam@bilgeadam.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> +90(555) 444 22 11 </p>
                        <p><i class="fas fa-phone me-3"></i> 444 0 444</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <!-- Copyright -->
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>